# Generated by Django 2.2.6 on 2019-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='send_date',
            field=models.DateTimeField(),
        ),
    ]
